### ISSUE TITLE
reference to github page not working

### ISSUE THREAD

**Issue by rbeldin** [RedHatNordicsSA/cool-lab#98]
Read the blog with interest: 

https://redhatnordicssa.github.io/rhel8-really-fast

There is a reference to this git hub repo: 

Clone the [https://github.com/mglantz/c_vm](https://redhatnordicssa.github.io/c_vm) GitHub repository:

But that repo cannot be referenced: 

`404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)`

**Comment by mskott** [comment]
Thanks for the heads up, the link has been fixed now :)
